openstack-config --set undercloud.conf DEFAULT local_ip 192.0.2.1/24
openstack-config --set undercloud.conf DEFAULT image_path /home/stack/images
openstack-config --set undercloud.conf DEFAULT network_gateway 192.0.2.1
openstack-config --set undercloud.conf DEFAULT undercloud_public_vip 192.0.2.2
openstack-config --set undercloud.conf DEFAULT undercloud_admin_vip 192.0.2.3
openstack-config --set undercloud.conf DEFAULT local_interface eth1
openstack-config --set undercloud.conf DEFAULT network_cidr 192.0.2.0/24
openstack-config --set undercloud.conf DEFAULT masquerade_network 192.0.2.0/24
openstack-config --set undercloud.conf DEFAULT dhcp_start 192.0.2.5
openstack-config --set undercloud.conf DEFAULT dhcp_end 192.0.2.24
openstack-config --set undercloud.conf DEFAULT inspection_interface br-ctlplane
openstack-config --set undercloud.conf DEFAULT inspection_iprange 192.0.2.100,192.0.2.120
openstack-config --set undercloud.conf DEFAULT inspection_extras false
openstack-config --set undercloud.conf DEFAULT inspection_runbench false
openstack-config --set undercloud.conf DEFAULT undercloud_debug true
openstack-config --set undercloud.conf DEFAULT enable_tempest true
openstack-config --set undercloud.conf DEFAULT ipxe_deploy true
openstack-config --set undercloud.conf DEFAULT store_events false
